name = "MFit"
uuid = "b65eaea1-64bc-41c1-8769-7d54b65f7ee7"
authors = ["ManuelStapper <manuel.stapper@googlemail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
